### ISSUE TITLE
Terraform provider documentation is not accurate on terraform.io website

### ISSUE THREAD

**Issue by scoulomb** [terraform-providers/terraform-provider-infoblox#11]
Doc given on Terraform website for Terraform provider here:
https://www.terraform.io/docs/providers/infoblox/index.html

is not accurate, it should not be:

````shell script
provider "infoblox"{
INFOBLOX_USERNAME=infoblox
INFOBLOX_SERVER=10.0.0.1
INFOBLOX_PASSWORD=infoblox
}
````

but 

````shell script
provider "infoblox" {
username="admin"
server="10.0.0.1" 
password="infoblox"
}
````

This is aligned with Infoblox plugin code [here](https://github.com/terraform-providers/terraform-provider-infoblox/blob/328f438127673823fc574c7c9dfe75c82978b8bd/infoblox/provider.go).
Otherwise it will prompt for username, server and password.

I tried it here: https://github.com/scoulomb/myIaC/blob/master/terraform/infoblox/main.tf

Can we update the doc? What do you think?

Thank you

**Comment by scoulomb** [comment]
I had fixed it here: https://github.com/terraform-providers/terraform-provider-infoblox/pull/12
But this change has been embedded in  https://github.com/terraform-providers/terraform-provider-infoblox/pull/13 merged today:?

**Comment by AvRajath** [comment]
Closing this as the document is now updated
