### ISSUE TITLE
Provider params incorrect

### ISSUE THREAD

**Issue by CultClassik** [terraform-providers/terraform-provider-infoblox#7]
Using the provider with tf 0.12.26, I had to use:

provider "infoblox" {
server=""
username=""
password=""
}

NOT 
INFOBLOX_SERVER=""
INFOBLOX_USERNAME=""
INFOBLOX_PASSWORD=""

**Comment by CultClassik** [comment]
Also note, the examples are incomplete. They do not include the provider, which is where I tried to find the correct param names after TF warned that INFOBLOX_SERVER is not expected here, etc. Examples should be complete and usable.

**Comment by AvRajath** [comment]
Closing this issue as the document is now updated with appropriate parameters.
