### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ghalevy** [terraform-providers/terraform-provider-infoblox#9]
Getting this error on plan.

Error: rpc error: code = Unavailable desc = transport is closing

$ terraform --version
Terraform v0.12.26
+ provider.google v3.27.0
+ provider.infoblox v1.0.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.27. You can update by downloading from https://www.terraform.io/downloads.html

**Comment by surskitt** [comment]
I'm getting this error too. Why was the issue closed?
